### ISSUE TITLE
File is not defined in LetterApi

### ISSUE THREAD

**Issue by ad-m** [watchdogpolska/small-eod-sdk-javascript#10]
Broken line: https://github.com/watchdogpolska/small-eod-sdk-javascript/blob/master/src/model/Letter.js#L87

Variable preview:
```
{
  data: {
    id: 13,
    direction: 'IN',
    channel: null,
    final: true,
    date: '2020-10-07T03:34:34.119029Z',
    referenceNumber: '',
    institution: null,
    case: null,
    attachments: [],
    comment: '',
    excerpt: 'xxxx',
    documentType: null,
    createdOn: '2020-10-07T03:34:34.120660Z',
    createdBy: 1,
    modifiedOn: '2020-10-07T03:34:34.129862Z',
    modifiedBy: 1
  }
}
```

Stacktrace:
```
ReferenceError: File is not defined
    at Function.exports.constructFromObject (/home/adas/Devel/small_eod/gmail-importer/node_modules/small_eod_client/src/model/Letter.js:88:76)
    at Function.exports.convertToType (/home/adas/Devel/small_eod/gmail-importer/node_modules/small_eod_client/src/ApiClient.js:578:23)
    at exports.deserialize (/home/adas/Devel/small_eod/gmail-importer/node_modules/small_eod_client/src/ApiClient.js:389:20)
    at /home/adas/Devel/small_eod/gmail-importer/node_modules/small_eod_client/src/ApiClient.js:521:30
    at Request.callback (/home/adas/Devel/small_eod/gmail-importer/node_modules/superagent/lib/node/index.js:868:12)
    at /home/adas/Devel/small_eod/gmail-importer/node_modules/superagent/lib/node/index.js:1100:20
    at IncomingMessage.<anonymous> (/home/adas/Devel/small_eod/gmail-importer/node_modules/superagent/lib/node/parsers/json.js:22:7)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by ad-m** [comment]
@kuskoman, masz jakieś propozycje?
